# 加密货币合约分析交易系统配置文件

# 交易所配置
exchanges:
  gateio:
    api_key: "YOUR_API_KEY"  # 替换为您的API密钥
    secret_key: "YOUR_SECRET_KEY"  # 替换为您的密钥
    use_testnet: true  # 是否使用测试网络

# 交易对配置
symbols:
  - "BTC/USDT"
  - "ETH/USDT"
  - "SOL/USDT"
  - "BNB/USDT"
  - "XRP/USDT"

# 时间周期配置
timeframes:
  - "1m"
  - "5m"
  - "15m"
  - "30m"
  - "1h"
  - "4h"
  - "1d"

# 分析参数配置
analysis_params:
  # 均线参数
  ma_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
  
  # RSI参数
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  
  # KDJ参数
  kdj:
    k_period: 9
    d_period: 3
    j_period: 3
  
  # MACD参数
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  
  # 布林带参数
  bollinger:
    period: 20
    std_dev: 2

# 信号生成参数
signal_params:
  # 信号阈值
  thresholds:
    strong_buy: 80
    buy: 60
    neutral: 40
    sell: 20
    strong_sell: 0
  
  # 指标权重 (权重总和应为1)
  weights:
    trend: 0.3
    oscillators: 0.3
    volume: 0.2
    sentiment: 0.2

# 风险管理参数
risk_management:
  max_position_size: 0.25  # 最大仓位比例
  max_leverage: 10  # 最大杠杆倍数
  min_risk_reward: 1.5  # 最小风险回报比

# Telegram机器人配置
telegram:
  token: "YOUR_BOT_TOKEN"  # 替换为您的Telegram机器人Token
  chat_id: "YOUR_CHAT_ID"  # 替换为您的聊天ID
  enabled: false  # 是否启用Telegram通知

# 日志配置
logging:
  level: "INFO"  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "crypto_bot.log"  # 日志文件名

# 高级设置
advanced:
  data_update_interval: 60  # 数据更新间隔(秒)
  max_lookback_bars: 500  # 最大回溯K线数量
  enable_cloud_sync: false  # 是否启用云同步